# Generated by Django 4.2.6 on 2023-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_serial_number",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
    ]
