# Generated by Django 4.2.6 on 2023-11-16 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset_management", "0002_alter_asset_asset_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_purchase_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 16, 6, 48, 17, 42181)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
