# Generated by Django 4.2.6 on 2023-11-16 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset_management", "0003_alter_asset_asset_purchase_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_purchase_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 16, 6, 49, 15, 776548, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
