# Generated by Django 4.2.6 on 2023-11-16 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("asset_management", "0004_alter_asset_asset_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_purchase_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
